services:
  payload:
    image: iprosaude-local:latest
    container_name: iprosaude-site
    restart: always

    ports:
      - "3010:3000"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

    environment:
      DATABASE_URI: postgres://john:6d824a8fcb75e45621bded4328a9cb02@postgres:5432/iprosaude_site
      REDIS_URL: redis://redis:6379
      PAYLOAD_SECRET: 6d824a8fcb75e45621bded4328a9cb02
      NODE_ENV: production

    command: >
      sh -c "
      echo '--- ENV VARS ---';
      env | sed
        -e 's/DATABASE_URI=.*/DATABASE_URI=******/'
        -e 's/PAYLOAD_SECRET=.*/PAYLOAD_SECRET=******/';
      echo '--- END ENV VARS ---';
      node check-env.js &&
      node server.js
      "

    networks:
      - app

networks:
  app:
    external: true
    name: app
