import React from 'react';
import { HeroBlock } from './blocks/HeroBlock';
import { ContentBlock } from './blocks/ContentBlock';
import { FeaturesBlock } from './blocks/FeaturesBlock';
import { FormBlock } from './blocks/FormBlock';
import type { LandingPage } from '@/payload-types';

type Props = {
  layout: LandingPage['layout'];
};

export const RenderBlocks: React.FC<Props> = ({ layout }) => {
  if (!layout || !Array.isArray(layout) || layout.length === 0) {
    return null;
  }

  return (
    <div className="blocks-container">
      {layout.map((block, index) => {
        const { blockType } = block;

        // Ensure we have a unique key. In some cases block.id might exist if generated by Payload.
        // If not, use index (fallback).
        // Check if 'id' exists on block type.
        const key = (block as any).id || index;

        switch (blockType) {
          case 'hero':
            return <HeroBlock key={key} {...block} />;
          case 'content':
            return <ContentBlock key={key} {...block} />;
          case 'features':
            return <FeaturesBlock key={key} {...block} />;
          case 'form':
            return <FormBlock key={key} {...block} />;
          case 'cta':
            // Inline simple CTA or specific component.
            // Since we don't have CallToActionBlock, we render a basic one here or placeholder.
            const ctaBlock = block as any; // Cast to access specific fields if needed
             return (
              <div key={key} className="cta-block p-8 bg-gray-100 text-center">
                <h3 className="text-xl font-bold mb-4">{ctaBlock.label}</h3>
                <p className="mb-4">{ctaBlock.text}</p>
                {ctaBlock.url && (
                    <a href={ctaBlock.url} className="inline-block bg-blue-600 text-white px-6 py-2 rounded">
                        Action
                    </a>
                )}
              </div>
            );
          default:
            return null;
        }
      })}
    </div>
  );
};
