/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    media: Media;
    tratamentos: Tratamento;
    'landing-pages': LandingPage;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tratamentos: TratamentosSelect<false> | TratamentosSelect<true>;
    'landing-pages': LandingPagesSelect<false> | LandingPagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    settings: Settings;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome: string;
  role?: ('admin' | 'editor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tratamentos".
 */
export interface Tratamento {
  id: number;
  titulo: string;
  slug: string;
  descricao?: string | null;
  beneficios?:
    | {
        beneficio?: string | null;
        id?: string | null;
      }[]
    | null;
  imagemDestaque?: (number | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages".
 */
export interface LandingPage {
  id: number;
  title: string;
  slug: string;
  showFloatingButton?: boolean | null;
  layout: (
    | {
        heading: string;
        text?: string | null;
        backgroundImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        title: string;
        subtitle?: string | null;
        botao?: {
          texto?: string | null;
          url?: string | null;
          cor?: ('verde' | 'dourado' | 'vermelho') | null;
        };
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero-gold';
      }
    | {
        content?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        features?:
          | {
              icone?: (number | null) | Media;
              title?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
    | {
        items?:
          | {
              name?: string | null;
              testimonial?: string | null;
              rating?: number | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        formId?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'form';
      }
    | {
        text?: string | null;
        botao?: {
          label?: string | null;
          url?: string | null;
          style?: ('default' | 'urgent' | 'whatsapp') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        title?: string | null;
        description?: string | null;
        tratamentosSelecionados?: (number | Tratamento)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'treatmentList';
      }
    | {
        layout?: ('default' | 'reverse') | null;
        beforeImage: number | Media;
        afterImage: number | Media;
        labelBefore?: string | null;
        labelAfter?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'beforeAfter';
      }
    | {
        titulo?: string | null;
        perguntas?:
          | {
              pergunta: string;
              resposta: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        tituloSessao?: string | null;
        membros?:
          | {
              nome?: string | null;
              cro?: string | null;
              especialidade?: string | null;
              descricao?: string | null;
              foto?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'team';
      }
    | {
        titulo?: string | null;
        endereco?: string | null;
        horario?: string | null;
        mapUrl?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'location';
      }
    | {
        headline?: string | null;
        nomeProfissional?: string | null;
        credenciais?: string | null;
        registro?: string | null;
        descricao?: string | null;
        fotoAutoridade?: (number | null) | Media;
        numerosDeSucesso?:
          | {
              numero?: string | null;
              legenda?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'authority';
      }
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tratamentos';
        value: number | Tratamento;
      } | null)
    | ({
        relationTo: 'landing-pages';
        value: number | LandingPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tratamentos_select".
 */
export interface TratamentosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  descricao?: T;
  beneficios?:
    | T
    | {
        beneficio?: T;
        id?: T;
      };
  imagemDestaque?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-pages_select".
 */
export interface LandingPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  showFloatingButton?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              text?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        'hero-gold'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              botao?:
                | T
                | {
                    texto?: T;
                    url?: T;
                    cor?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              features?:
                | T
                | {
                    icone?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              items?:
                | T
                | {
                    name?: T;
                    testimonial?: T;
                    rating?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              formId?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              text?: T;
              botao?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                  };
              id?: T;
              blockName?: T;
            };
        treatmentList?:
          | T
          | {
              title?: T;
              description?: T;
              tratamentosSelecionados?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              layout?: T;
              beforeImage?: T;
              afterImage?: T;
              labelBefore?: T;
              labelAfter?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              titulo?: T;
              perguntas?:
                | T
                | {
                    pergunta?: T;
                    resposta?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              tituloSessao?: T;
              membros?:
                | T
                | {
                    nome?: T;
                    cro?: T;
                    especialidade?: T;
                    descricao?: T;
                    foto?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        location?:
          | T
          | {
              titulo?: T;
              endereco?: T;
              horario?: T;
              mapUrl?: T;
              id?: T;
              blockName?: T;
            };
        authority?:
          | T
          | {
              headline?: T;
              nomeProfissional?: T;
              credenciais?: T;
              registro?: T;
              descricao?: T;
              fotoAutoridade?: T;
              numerosDeSucesso?:
                | T
                | {
                    numero?: T;
                    legenda?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
  id: number;
  analytics?: {
    headerScripts?: string | null;
    bodyScripts?: string | null;
  };
  contact?: {
    whatsapp?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  analytics?:
    | T
    | {
        headerScripts?: T;
        bodyScripts?: T;
      };
  contact?:
    | T
    | {
        whatsapp?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}